name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Usamos la acción oficial empaquetada que ya incluye AIDL y todas las herramientas sin fallos de rutas
      - name: Build APK with Buildozer Action
        uses: Artemis-Skade/buildozer-action@v1
        with:
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/calculadora/build/outputs/apk/debug/*.apk
