name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Android Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libssl-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0.0" virtualenv buildozer

      # Le enviamos un "y" automático al distclean para que no pida confirmación manual
      - name: Clean Cache
        run: echo "y" | buildozer distclean

      # Forzar la aceptación de licencias del SDK de Android sin colapsar la consola
      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # CORRECCIÓN AQUÍ: Exportamos PATH y ANDROID_HOME globalmente para que Buildozer localice 'aidl'
      - name: Build APK
        env:
          APP_ALLOW_ROOT: "1"
          BUILDOZER_ALLOW_KIVY_DEVELOP_BRANCH: "1"
        run: |
          # Buscamos la última versión de build-tools instalada en el servidor y la inyectamos al sistema
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          export PATH=$PATH:$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/calculadora/build/outputs/apk/debug/*.apk
